### ISSUE TITLE
Staging tasks are failing with "Disconnected" messages to Warden

### ISSUE THREAD

**Issue by fraenkel** [cloudfoundry/dea_ng#165]
An idle timer is set on the connection to Warden when there are no outstanding requests. However, the way the DEA acquires a warden connection does not prevent it from retrieving a Disconnected connection or being disconnected while using it.

The best solution is to remove the idle timer since it serves no real purpose. We don't have many connections to Warden, 3 or so. We could increase the timeout but this problem will still occur.

The problem does occur most frequently with the Java buildpack/Tomcat where it has a long download for artifacts. Below is a snippet of the logs.

```
{"timestamp":1431225565.530343,"message":"staging.task.execute-staging","log_level":"debug","source":"Staging","data":{"app_guid":"25b6b2e0-e01d-4714-972d-996a1789fcc1","task_id":"df72259ac08f4bf99f05dba87a9d5fa0","script":"set -o pipefail; export VCAP_APPLICATION=\\{\\\"limits\\\":\\{\\\"mem\\\":512,\\\"disk\\\":1024,\\\"fds\\\":16384\\},\\\"application_version\\\":\\\"4bc46693-7d6e-4824-886a-19c07c627f2e\\\",\\\"application_name\\\":\\\"A1-StatusTestApp1431225546492\\\",\\\"application_uris\\\":\\[\\\"A1-StatusTestApp1431225546492.stage1.ng.bluemix.net\\\"\\],\\\"version\\\":\\\"4bc46693-7d6e-4824-886a-19c07c627f2e\\\",\\\"name\\\":\\\"A1-StatusTestApp1431225546492\\\",\\\"space_name\\\":\\\"uptime\\\",\\\"space_id\\\":\\\"900f5c68-0910-4faf-84ed-24c0b805a9dd\\\",\\\"uris\\\":\\[\\\"A1-StatusTestApp1431225546492.stage1.ng.bluemix.net\\\"\\],\\\"users\\\":null\\};\nexport VCAP_SERVICES=\\{\\};\nexport MEMORY_LIMIT=\"512m\";\nexport BUILDPACK_CACHE=\"/var/vcap/packages/buildpack_cache\";\nexport STAGING_TIMEOUT=\"900.0\";\nexport MEMORY_LIMIT=\"512m\";\nexport CF_STACK=\"lucid64\";\n /usr/bin/ruby /var/vcap/packages/dea_next/buildpacks/bin/run /var/vcap/data/dea_next/staging/d20150510-13604-ta5qyn/plugin_config | tee -a /tmp/staged/logs/staging_task.log"},"thread_id":70230060757760,"fiber_id":70230188194260,"process_id":13604,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":222,"method":"block in promise_stage"}
{"timestamp":1431225565.542062,"message":"snapshot_attributes","log_level":"debug","source":"Staging","data":{"app_guid":"25b6b2e0-e01d-4714-972d-996a1789fcc1","task_id":"df72259ac08f4bf99f05dba87a9d5fa0","properties":{"services":[],"resources":{"memory":512,"disk":1024,"fds":16384},"environment":["CF_STACK=lucid64"],"meta":{"console":false},"buildpack_key":"0041b66c-cc13-4b5e-91b8-45472142037b_cf07d48f2d45a0eeb02b56c56e9a39cee81044b3"}},"thread_id":70230060757760,"fiber_id":70230188194260,"process_id":13604,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":502,"method":"snapshot_attributes"}
{"timestamp":1431225597.5597432,"message":"staging.task.packing-droplet","log_level":"info","source":"Staging","data":{"app_guid":"25b6b2e0-e01d-4714-972d-996a1789fcc1","task_id":"df72259ac08f4bf99f05dba87a9d5fa0"},"thread_id":70230060757760,"fiber_id":70230080860460,"process_id":13604,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":287,"method":"block in promise_pack_app"}
{"timestamp":1431225597.5608807,"message":"staging.task-info.copying-out","log_level":"info","source":"Staging","data":{"app_guid":"25b6b2e0-e01d-4714-972d-996a1789fcc1","task_id":"df72259ac08f4bf99f05dba87a9d5fa0","source":"/tmp/staged/staging_info.yml","destination":"/var/vcap/data/dea_next/staging/d20150510-13604-ta5qyn/staging_info.yml"},"thread_id":70230060757760,"fiber_id":70230079329860,"process_id":13604,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":263,"method":"block in promise_staging_info"}
{"timestamp":1431225599.243332,"message":"staging.task-log.copying-out","log_level":"info","source":"Staging","data":{"app_guid":"25b6b2e0-e01d-4714-972d-996a1789fcc1","task_id":"df72259ac08f4bf99f05dba87a9d5fa0","source":"/tmp/staged/logs/staging_task.log","destination":"/var/vcap/data/dea_next/staging/d20150510-13604-ta5qyn/staging_task.log"},"thread_id":70230060757760,"fiber_id":70230120371960,"process_id":13604,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":254,"method":"block in promise_task_log"}
{"timestamp":1431225599.4826744,"message":"staging.task.failed","log_level":"info","source":"Staging","data":{"app_guid":"25b6b2e0-e01d-4714-972d-996a1789fcc1","task_id":"df72259ac08f4bf99f05dba87a9d5fa0","error":"Disconnected","backtrace":["/var/vcap/packages/dea_next/vendor/cache/warden-ad18bff7dc56/em-warden-client/lib/em/warden/client/connection.rb:27:in `get'","/var/vcap/packages/dea_next/vendor/cache/warden-ad18bff7dc56/em-warden-client/lib/em/warden/client.rb:46:in `call'","/var/vcap/packages/dea_next/lib/container/container.rb:192:in `call'","/var/vcap/packages/dea_next/lib/container/container.rb:72:in `run_script'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:289:in `block in promise_pack_app'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `call'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `block in
```

**Comment by jpalermo** [comment]
Where are we setting this idle timer? I can't find it in the source.

**Comment by fraenkel** [comment]
Its all in warden-client hence the linked PR over to it.

**Comment by zaksoup** [comment]
Seems like the solution was merged in. Closing this unless I'm wrong in which case @fraenkel or @jpalermo can reopen and continue to discuss.

**Comment by fraenkel** [comment]
Whoa... The merge is false. It was reverted.

**Comment by zaksoup** [comment]
Yeah @fraenkel hadn't seen that. Was reverted in https://github.com/cloudfoundry/warden/commit/e8f31ee5e40df69199ca3d69b8d909397f5b5365. Seems to have been causing CPU spikes. I'll circle up with those team members and get this party (discussion) started.

**Comment by zaksoup** [comment]
ping @wendorf @zrob

**Comment by zaksoup** [comment]
what's happening here. Who knows what's going on? I have no context.

**Comment by Amit-PivotalLabs** [comment]
Looks like this is in now: https://github.com/cloudfoundry/warden/commit/d9065ba9df3261517a2ababdb66ca22345d4b94d.  Closing.
