### ISSUE TITLE
Starting failure with 504

### ISSUE THREAD

**Issue by Yancey1989** [cloudfoundry/dea_ng#173]
Hi!
cf push xxx with cli

cf_release version:212
os:ubuntu12.04
deploy with cf_nise_installer

```
Updating app hello-python in org DevBox / space bre as admin...
OK

Uploading hello-python...
Uploading app files from: /home/cf/xu.yan/hello-python
Uploading 2.7K, 7 files
Done uploading               
OK

Stopping app hello-python in org DevBox / space bre as admin...
OK

Starting app hello-python in org DevBox / space bre as admin...
FAILED
Server error, status code: 504, error code: 0, message: 
```

in de_next.log
```

{"timestamp":1442731880.415194,"message":"staging.task.failed","log_level":"info","source":"Staging","data":{"app_guid":"175d577d-46c4-4311-899f-eacdae64d164","task_id":"02f394d2b5b24d56a8bcdf4ff0618c9e","error":"command exited with failure","backtrace":["/var/vcap/packages/dea_next/vendor/cache/warden-ad18bff7dc56/em-warden-client/lib/em/warden/client/connection.rb:27:in `get'","/var/vcap/packages/dea_next/vendor/cache/warden-ad18bff7dc56/em-warden-client/lib/em/warden/client.rb:46:in `call'","/var/vcap/packages/dea_next/lib/container/container.rb:192:in `call'","/var/vcap/packages/dea_next/lib/container/container.rb:153:in `block in new_container_with_bind_mounts_and_rootfs'","/var/vcap/packages/dea_next/lib/container/container.rb:229:in `call'","/var/vcap/packages/dea_next/lib/container/container.rb:229:in `with_em'","/var/vcap/packages/dea_next/lib/container/container.rb:137:in `new_container_with_bind_mounts_and_rootfs'","/var/vcap/packages/dea_next/lib/container/container.rb:120:in `block in create_container'","/var/vcap/packages/dea_next/lib/container/container.rb:229:in `call'","/var/vcap/packages/dea_next/lib/container/container.rb:229:in `with_em'","/var/vcap/packages/dea_next/lib/container/container.rb:119:in `create_container'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:543:in `resolve_staging_setup'","/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb:49:in `block in start'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `call'","/var/vcap/packages/dea_next/lib/dea/promise.rb:92:in `block in run'"]},"thread_id":69965282702100,"fiber_id":69965294576760,"process_id":44238,"file":"/var/vcap/packages/dea_next/lib/dea/staging/staging_task.rb","lineno":57,"method":"block in start"}
{"timestamp":1442731880.4168656,"message":"task.destroy.invalid","log_level":"error","source":"Staging","data":{"app_guid":"175d577d-46c4-4311-899f-eacdae64d164","task_id":"02f394d2b5b24d56a8bcdf4ff0618c9e"},"thread_id":69965282702100,"fiber_id":69965294368660,"process_id":44238,"file":"/var/vcap/packages/dea_next/lib/dea/task.rb","lineno":66,"method":"block in promise_destroy"}
root@bjlg-80p50-cf-02:/var/vcap/sys/log/dea_next# 
```

in warden.log
```
{"timestamp":1442731879.5131524,"message":"Container created","log_level":"debug","source":"Warden::Container::Linux","data":{"handle":"18vtqk14egk"},"thread_id":69932978885420,"fiber_id":69932978855160,"process_id":28688,"file":"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/lib/warden/container/linux.rb","lineno":102,"method":"do_create"}
{"timestamp":1442731880.101295,"message":"Exited with status 1 (0.587s): [[\"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/src/closefds/closefds\", \"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/src/closefds/closefds\"], \"/var/vcap/data/warden/depot/18vtqk14egk/start.sh\"]","log_level":"warn","source":"Warden::Container::Linux","data":{"handle":"18vtqk14egk","stdout":"","stderr":""},"thread_id":69932978885420,"fiber_id":69932991380440,"process_id":28688,"file":"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/lib/warden/container/spawn.rb","lineno":135,"method":"set_deferred_success"}
{"timestamp":1442731880.104105,"message":"Exited with status 255 (0.001s): [[\"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/src/closefds/closefds\", \"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/src/closefds/closefds\"], \"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/root/linux/stop.sh\", \"/var/vcap/data/warden/depot/18vtqk14egk\", \"-w\", \"0\"]","log_level":"warn","source":"Warden::Container::Linux","data":{"handle":"18vtqk14egk","stdout":"","stderr":"execvp: No such file or directory\n"},"thread_id":69932978885420,"fiber_id":69932991380440,"process_id":28688,"file":"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/lib/warden/container/spawn.rb","lineno":135,"method":"set_deferred_success"}
{"timestamp":1442731880.412572,"message":"Container destroyed","log_level":"debug","source":"Warden::Container::Linux","data":{"handle":"18vtqk14egk"},"thread_id":69932978885420,"fiber_id":69932978855160,"process_id":28688,"file":"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/lib/warden/container/linux.rb","lineno":125,"method":"do_destroy"}
{"timestamp":1442731880.4129846,"message":"destroy (took 0.311137)","log_level":"debug","source":"Warden::Container::Linux","data":{"handle":"18vtqk14egk","request":{},"response":{}},"thread_id":69932978885420,"fiber_id":69932978855160,"process_id":28688,"file":"/var/vcap/data/packages/warden/724f030f2d6e90d02c2afbe90ed5fe1ce2de1667/warden/lib/warden/container/base.rb","lineno":300,"method":"dispatch"}
```

Could anyone can help with this issue?

**Comment by Amit-PivotalLabs** [comment]
According to @lexsys27:

> Ubuntu 14.04 is required for cf_nise_installer [1]. Can you upgrade your host OS and see if issue persists? 

> [1]: https://github.com/yudai/cf_nise_installer

**Comment by Yancey1989** [comment]
Hi
I have already success running on ubuntu 12 for about two weeks...
and I reinstall on the machine with the follow steps:
1) /var/vcap/bosh/bin/monit stop all
2) kill monit process
3) rm -rf /var/vcap
4) cd {cf_nise_installer} && ./script/install.sh
but the error doesn’t fixed…

**Comment by njbennett** [comment]
Did you change anything from when it was working before?

**Comment by zaksoup** [comment]
Hi @Yancey1989 do you have any updates? Can you give us more information about what you had installed before you started seeing this failure and what changed? Have you tried upgrading to 14.04?

**Comment by jpalermo** [comment]
Closing due to inactivity. Please reopen if you have more details.
