### ISSUE TITLE
DEA got stuck in endless loop during draining

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/dea_ng#178]
An update of a deployment for cf-release just failed with the following situation

* one of the DEAs could not be shut down successfully and the director kept calling it
* on the DEA, we saw that `drain` was called over and over again
  Output of `/var/vcap/monit/monit.log`:

  ```
  [UTC Nov  4 15:36:02] info     : unmonitor service 'metron_agent' on user request
  [UTC Nov  4 15:36:02] info     : monit daemon at 1714 awakened
  [UTC Nov  4 15:36:02] info     : Awakened by User defined signal 1
  [UTC Nov  4 15:36:02] info     : unmonitor service 'dea_logging_agent' on user request
  [UTC Nov  4 15:36:02] info     : monit daemon at 1714 awakened
  [UTC Nov  4 15:36:02] info     : unmonitor service 'dir_server' on user request
  [UTC Nov  4 15:36:02] info     : monit daemon at 1714 awakened
  [UTC Nov  4 15:36:02] info     : unmonitor service 'dea_next' on user request
  [UTC Nov  4 15:36:02] info     : monit daemon at 1714 awakened
  [UTC Nov  4 15:36:02] info     : unmonitor service 'warden' on user request
  [UTC Nov  4 15:36:02] info     : monit daemon at 1714 awakened
  [UTC Nov  4 15:36:02] info     : 'warden' unmonitor action done
  [UTC Nov  4 15:36:02] info     : 'dea_next' unmonitor action done
  [UTC Nov  4 15:36:02] info     : 'dir_server' unmonitor action done
  [UTC Nov  4 15:36:02] info     : 'dea_logging_agent' unmonitor action done
  [UTC Nov  4 15:36:03] info     : 'metron_agent' unmonitor action done
  [UTC Nov  4 15:36:13] info     : Awakened by User defined signal 1
  ```

  So monit did no longer watch the DEA. `dea_next` was however still running and having a PID.

* Output of the drain log:

  ```
  # Logfile created on 2015-11-04 15:36:02 +0000 by logger.rb/44203
  I, [2015-11-04T15:36:02.872085 #8554]  INFO -- : Drain script invoked with job_changed hash_changed dea_next
  I, [2015-11-04T15:36:02.872178 #8554]  INFO -- : Sending signal USR2 to DEA.
  I, [2015-11-04T15:36:02.872480 #8554]  INFO -- : Hey BOSH, call me back in 5s.
  I, [2015-11-04T15:36:07.891336 #8565]  INFO -- : Drain script invoked with job_check_status hash_unchanged
  I, [2015-11-04T15:36:07.891476 #8565]  INFO -- : Sending signal USR2 to DEA.
  I, [2015-11-04T15:36:07.893744 #8565]  INFO -- : Hey BOSH, call me back in 5s.
  (...)
  I, [2015-11-05T14:36:41.165410 #32412]  INFO -- : Hey BOSH, call me back in 5s.
  I, [2015-11-05T14:36:46.184061 #32415]  INFO -- : Drain script invoked with job_check_status hash_unchanged
  I, [2015-11-05T14:36:46.184202 #32415]  INFO -- : Sending signal USR2 to DEA.
  I, [2015-11-05T14:36:46.184991 #32415]  INFO -- : Hey BOSH, call me back in 5s.
  I, [2015-11-05T14:36:51.202124 #32418]  INFO -- : Drain script invoked with job_check_status hash_unchanged
  I, [2015-11-05T14:36:51.202249 #32418]  INFO -- : Sending signal USR2 to DEA.
  I, [2015-11-05T14:36:51.203019 #32418]  INFO -- : Hey BOSH, call me back in 5s.
  ```

  * Output of `/var/vcap/job/dea_next/dea_next.log`
  
  ```
  {"timestamp":1446627315.5881095,"message":"Dea started","log_level":"info","source":"Dea::Bootstrap","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/bootstrap.rb","lineno":135,"method":"setup_logging"}
    {"timestamp":1446627315.6084383,"message":"nats.connecting","log_level":"info","source":"Dea::Nats","data":{"servers":["nats://nats@10.1.1.3:4222"]},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/nats.rb","lineno":103,"method":"create_nats_client"}
  {"timestamp":1446651362.87298,"message":"caught SIGUSR2","log_level":"warn","source":"Dea::Bootstrap","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/signal_handler.rb","lineno":25,"method":"block (3 levels) in setup"}
  {"timestamp":1446651362.873398,"message":"Evacuating (first time: true; can shutdown: true)","log_level":"info","source":"EvacuationHandler","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/evacuation_handler.rb","lineno":15,"method":"evacuate!"}
  {"timestamp":1446651362.87391,"message":"All instances and staging tasks stopped, exiting.","log_level":"info","source":"Dea::Bootstrap","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/shutdown_handler.rb","lineno":46,"method":"flush_message_bus_and_terminate"}
  {"timestamp":1446651367.895091,"message":"caught SIGUSR2","log_level":"warn","source":"Dea::Bootstrap","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/signal_handler.rb","lineno":25,"method":"block (3 levels) in setup"}
  {"timestamp":1446651367.8955498,"message":"Evacuating (first time: false; can shutdown: true)","log_level":"info","source":"EvacuationHandler","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/evacuation_handler.rb","lineno":15,"method":"evacuate!"}
  {"timestamp":1446651372.9151535,"message":"caught SIGUSR2","log_level":"warn","source":"Dea::Bootstrap","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/signal_handler.rb","lineno":25,"method":"block (3 levels) in setup"}
  {"timestamp":1446651372.9153638,"message":"Evacuating (first time: false; can shutdown: true)","log_level":"info","source":"EvacuationHandler","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/evacuation_handler.rb","lineno":15,"method":"evacuate!"}
  {"timestamp":1446651377.934596,"message":"caught SIGUSR2","log_level":"warn","source":"Dea::Bootstrap","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/signal_handler.rb","lineno":25,"method":"block (3 levels) in setup"}
  {"timestamp":1446651377.9348934,"message":"Evacuating (first time: false; can shutdown: true)","log_level":"info","source":"EvacuationHandler","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/evacuation_handler.rb","lineno":15,"method":"evacuate!"}
  {"timestamp":1446651382.9552572,"message":"caught SIGUSR2","log_level":"warn","source":"Dea::Bootstrap","data":{},"thread_id":70008570680120,"fiber_id":70008581144080,"process_id":6765,"file":"/var/vcap/packages/dea_next/lib/dea/lifecycle/signal_handler.rb","lineno":25,"method":"block (3 levels) in setup”}
  ```

* In the end, we ended up killing the `dea_next` process and cancelled the `bosh deploy` task, this is the bosh task output

  ```
  , [2015-11-05 14:39:07 #13431] [task:369] DEBUG -- DirectorJobRunner: SENT: hm.director.alert   {"id":"7f82f8a0-7430-45a3-bd8c-5a51e41f76bf","severity":3,"title":"director - error during update deployment","summary":"Error during update deployment for 'cf' against Director '0cb35106-47c1-4b29-bd9e-11991a538e14': #<Bosh::Director::RpcRemoteException: Action Failed get_task: Task 89cd94ac-e9df-43ca-6e19-3de624db9630 result: Stopping Monitored Services: Stopping service statsd-injector: Sending stop request to monit: Request failed, response: Response{ StatusCode: 503, Status: '503 Service Unavailable' }>","created_at":1446734347}
  E, [2015-11-05 14:39:07 #13431] [task:369] ERROR -- DirectorJobRunner: Action Failed get_task: Task 89cd94ac-e9df-43ca-6e19-3de624db9630 result: Stopping Monitored Services: Stopping service statsd-injector: Sending stop request to monit: Request failed, response: Response{ StatusCode: 503, Status: '503 Service Unavailable' }
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/agent_client.rb:231:in `handle_method'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/agent_client.rb:286:in `handle_message_with_retry'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/agent_client.rb:58:in `method_missing'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/agent_client.rb:310:in `get_task_status'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/agent_client.rb:155:in `wait_for_task'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/agent_client.rb:299:in `send_message'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/agent_client.rb:142:in `stop'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/instance_updater/stopper.rb:19:in `stop'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/instance_updater.rb:144:in `stop'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/instance_updater.rb:50:in `block in update_steps'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/instance_updater.rb:88:in `call'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/instance_updater.rb:88:in `block in update'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/instance_updater.rb:87:in `each'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/instance_updater.rb:87:in `update'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/job_updater.rb:74:in `block (2 levels) in update_canary_instance'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3122.0/lib/common/thread_formatter.rb:49:in `with_thread_name'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/job_updater.rb:72:in `block in update_canary_instance'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/event_log.rb:97:in `call'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/event_log.rb:97:in `advance_and_track'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/job_updater.rb:71:in `update_canary_instance'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh-director-1.3122.0/lib/bosh/director/job_updater.rb:65:in `block (2 levels) in update_canaries'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3122.0/lib/common/thread_pool.rb:77:in `call'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3122.0/lib/common/thread_pool.rb:77:in `block (2 levels) in create_thread'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3122.0/lib/common/thread_pool.rb:63:in `loop'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/bosh_common-1.3122.0/lib/common/thread_pool.rb:63:in `block in create_thread'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `call'
  /var/vcap/packages/director/gem_home/ruby/2.1.0/gems/logging-1.8.2/lib/logging/diagnostic_context.rb:323:in `block in create_with_logging_context'
  D, [2015-11-05 14:39:07 #13431] [task:369] DEBUG -- DirectorJobRunner: (0.000167s) SELECT NULL
  D, [2015-11-05 14:39:07 #13431] [task:369] DEBUG -- DirectorJobRunner: (0.000105s) BEGIN
  D, [2015-11-05 14:39:07 #13431] [task:369] DEBUG -- DirectorJobRunner: (0.000438s) UPDATE "tasks" SET "state" = 'error', "timestamp" = '2015-11-05 14:39:07.761320+0000', "description" = 'create deployment', "result" = 'Action Failed get_task: Task 89cd94ac-e9df-43ca-6e19-3de624db9630 result: Stopping Monitored Services: Stopping service...', "output" = '/var/vcap/store/director/tasks/369', "checkpoint_time" = '2015-11-05 14:38:53.853706+0000', "type" = 'update_deployment', "username" = 'admin' WHERE ("id" = 369)
  D, [2015-11-05 14:39:07 #13431] [task:369] DEBUG -- DirectorJobRunner: (0.001456s) COMMIT
I, [2015-11-05 14:39:07 #13431] []  INFO -- DirectorJobRunner: Task took 23 hours 9 minutes 47.2267992279958 seconds to process.
  ```

Apparently, [evacuation_handler.evacuate!](https://github.com/cloudfoundry/dea_ng/blob/master/lib/dea/lifecycle/evacuation_handler.rb#L12-L23) was executed over and over again and because `@evacuation_processed` was already set to `true` it didn't actually try to shutdown the process again. I have no idea why it didn't shut down the DEA the first time.

Any thoughts, suggestions? Where could I have looked to find the root cause for this?
cc @cppforlife

**Comment by zaksoup** [comment]
This looks like something blew up somewhere in the nats client and `terminate` was never actually called. https://github.com/cloudfoundry/dea_ng/blob/5381c9561137258d7a97fdc488a90aa0d25a527d/lib/dea/lifecycle/shutdown_handler.rb#L47

I'm not sure that the NAT client logs would be separate from the DEA logs so it looks like it failed silently and never called `terminate` in the block that was passed in.

Other than letting us know about this I don't know what else there is to do at this point. If we still had the DEA running we might be able to look into it and figure out what happened in the NATs client but I assume you've killed it.

@zaksoup and @ryanmoran

**Comment by voelzmo** [comment]
Unfortunately, the DEA is no longer around, yes. If that happens again, where would I get additional debug information from? I didn't find any logs related to NATS errors in the DEA logs, afaik.

**Comment by ryanmoran** [comment]
There may be some more useful debug information in the NATS logs. Other than that, the issue seems isolated to those two components (DEA and NATS), so I would expect all of the debug info to be in the logs for either of those VMs.

**Comment by voelzmo** [comment]
Alright, thanks for the hints, I'll try to find some more debug infos the next time.

What still bothers me is that there is no timeout for a hard shutdown and messages are not re-sent. The message was only sent once (and lost as it seems) – so this should probably time out at some point in time. Alternatively, you could re-send the `ready for termination` message. Wdyt?

**Comment by zaksoup** [comment]
@voelzmo my reading of the code path involved is that this isn't due to a lost nats message but rather the block passed as a callback to flush never having been called. In this case resending the `ready for termination message` would not solve that problem. A hard timeout in the monit ctl script would probably do it, however, given the deprecated nature of the DEA I don't think we're going to be prioritizing any stories to solve this in the near future. If this becomes a painful recurring problem we can revisit that, and we'd also be more than happy to pull in a pull request.

**Comment by voelzmo** [comment]
@zaksoup Thanks for the details. I was under the impression that [this line](https://github.com/cloudfoundry/dea_ng/blob/master/lib/dea/lifecycle/evacuation_handler.rb#L16) in the evacuation_hanlder might be one of the problems, as it is only executed the first time and then never again even if it failed.

**Comment by zaksoup** [comment]
@voelzmo I see what you're saying about the `send_shutdown` call. The reason it's written that way is because it's normal for evacuation to take longer than monit's retry delay and we don't want to be sending the shutdown message again while evacuation is in progress. This is definitely not the most elegant way of solving that problem but like I said, unless this is a reoccurring pain for you I'm not sure it's a priority for our team.

**Comment by ryanmoran** [comment]
@voelzmo in an effort to close out issues, we are going to resolve this issue. If you continue to see this problem and have some more details as to what you think might be happening, feel free to reopen the issue. Thanks!
