### ISSUE TITLE
No logs when app crashes during startup

### ISSUE THREAD

**Issue by voelzmo** [cloudfoundry/dea_ng#181]
When an application crashes during startup, there are no logs available to the user to give her an idea what actually went wrong. Here is a recent example:

```
2015-12-17T14:28:52.33+0100 [API/0]      OUT Updated app with guid daae243e-0151-4314-8ac9-7cf47c90a3a7 ({"state"=>"STOPPED"})
2015-12-17T14:28:52.77+0100 [DEA/8]      OUT Got staging request for app with id daae243e-0151-4314-8ac9-7cf47c90a3a7
2015-12-17T14:29:02.37+0100 [API/0]      OUT Updated app with guid daae243e-0151-4314-8ac9-7cf47c90a3a7 ({"state"=>"STARTED"})
2015-12-17T14:29:15.87+0100 [STG/8]      OUT -----> Downloaded app package (901M)
2015-12-17T14:29:16.68+0100 [STG/8]      OUT -----> Downloaded app buildpack cache (44M)
2015-12-17T14:29:33.88+0100 [STG/0]      OUT -----> Java Buildpack Version: v3.0 | https://github.com/cloudfoundry/java-buildpack.git#3bd15e1
2015-12-17T14:29:34.21+0100 [STG/0]      OUT -----> Downloading Open Jdk JRE 1.8.0_65 from https://download.run.pivotal.io/openjdk/trusty/x86_64/openjdk-1.8.0_65.tar.gz (found in cache)
2015-12-17T14:29:39.65+0100 [STG/0]      OUT        Expanding Open Jdk JRE to .java-buildpack/open_jdk_jre (5.4s)
2015-12-17T14:29:39.71+0100 [STG/0]      OUT -----> Downloading Spring Auto Reconfiguration 1.10.0_RELEASE from https://download.run.pivotal.io/auto-reconfiguration/auto-reconfiguration-1.10.0_RELEASE.jar (found in cache)
2015-12-17T14:29:41.73+0100 [STG/0]      ERR 
2015-12-17T14:31:18.97+0100 [STG/8]      OUT -----> Uploading droplet (945M)
2015-12-17T14:33:10.08+0100 [DEA/8]      OUT Starting app instance (index 0) with guid daae243e-0151-4314-8ac9-7cf47c90a3a7
2015-12-17T14:33:31.87+0100 [API/0]      OUT App instance exited with guid daae243e-0151-4314-8ac9-7cf47c90a3a7 payload: {"cc_partition"=>"default", "droplet"=>"daae243e-0151-4314-8ac9-7cf47c90a3a7", "version"=>"d2c72d59-55cd-46ca-96b0-1ea074774e6f", "instance"=>"fdeffa6ad2d0496b97628ad2f470652c", "index"=>0, "reason"=>"CRASHED", "exit_status"=>-1, "exit_description"=>"failed to start", "crash_timestamp"=>1450359212}
2015-12-17T14:33:36.12+0100 [DEA/8]      OUT Removing crash for app with id daae243e-0151-4314-8ac9-7cf47c90a3a7
2015-12-17T14:33:36.12+0100 [DEA/8]      OUT Stopping app instance (index 0) with guid daae243e-0151-4314-8ac9-7cf47c90a3a7
2015-12-17T14:33:36.17+0100 [DEA/8]      OUT Stopped app instance (index 0) with guid daae243e-0151-4314-8ac9-7cf47c90a3a7
```

As you can see, the pushed app was quite big (spring-boot generated fatjar) and seemingly exceeded the disk_quota on the DEA which was set to 1G during startup. 

Another recent example was a dependency problem where the app itself crashed during startup. The same problem occurred: No logs telling the user what the reason might have been.

Can we give the user some more information about what went wrong during startup if the app didn't come up successfully?

**Comment by Amit-PivotalLabs** [comment]
Hey @voelzmo 

Sorry for the delay.  Are you only seeing this issue on the DEAs, or Diego as well?

When you say you're not seeing logs to tell the user what might have happened, is this something your application could be logging?  I.e. your application would be better suited to give information about why it crashed, especially if it's some runtime exception, what sort of information would you expect to see from the DEA?

I have a go app that panics on start.  On Diego (and probably the DEA) I see a bunch of useful information, but it's coming from the app logs themselves:

```
2015-12-29T00:30:19.97-0800 [CELL/0]     OUT Creating container
2015-12-29T00:30:20.67-0800 [CELL/0]     OUT Successfully created container
2015-12-29T00:30:21.10-0800 [APP/0]      OUT listening...
2015-12-29T00:30:21.11-0800 [APP/0]      ERR panic: hi mom
2015-12-29T00:30:21.11-0800 [APP/0]      ERR goroutine 1 [running]:
2015-12-29T00:30:21.11-0800 [APP/0]      ERR main.main()
2015-12-29T00:30:21.11-0800 [APP/0]      ERR 	/tmp/app/.heroku/go/src/go-online/site.go:12 +0x14a
2015-12-29T00:30:21.11-0800 [APP/0]      ERR goroutine 2 [runnable]:
2015-12-29T00:30:21.11-0800 [APP/0]      ERR runtime.forcegchelper()
2015-12-29T00:30:21.11-0800 [APP/0]      ERR 	/usr/local/go/src/runtime/proc.go:90
2015-12-29T00:30:21.11-0800 [APP/0]      ERR runtime.goexit()
2015-12-29T00:30:21.11-0800 [APP/0]      ERR 	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
2015-12-29T00:30:21.11-0800 [APP/0]      ERR goroutine 3 [runnable]:
2015-12-29T00:30:21.11-0800 [APP/0]      ERR runtime.bgsweep()
2015-12-29T00:30:21.11-0800 [APP/0]      ERR 	/usr/local/go/src/runtime/mgc0.go:82
2015-12-29T00:30:21.11-0800 [APP/0]      ERR runtime.goexit()
2015-12-29T00:30:21.11-0800 [APP/0]      ERR 	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
2015-12-29T00:30:21.11-0800 [APP/0]      ERR goroutine 4 [runnable]:
2015-12-29T00:30:21.11-0800 [APP/0]      ERR runtime.runfinq()
2015-12-29T00:30:21.11-0800 [APP/0]      ERR 	/usr/local/go/src/runtime/malloc.go:712
2015-12-29T00:30:21.11-0800 [APP/0]      ERR runtime.goexit()
2015-12-29T00:30:21.11-0800 [APP/0]      ERR 	/usr/local/go/src/runtime/asm_amd64.s:2232 +0x1
2015-12-29T00:30:21.11-0800 [APP/0]      OUT Exit status 2
2015-12-29T00:30:21.11-0800 [CELL/0]     OUT Exit status 2
2015-12-29T00:30:21.29-0800 [API/3]      OUT App instance exited with guid 98d767d4-79ab-4270-9be0-9f6f0670ab2a payload: {"instance"=>"edddeef2-1c5d-4607-54c4-8b548c0e2f3a", "index"=>0, "reason"=>"CRASHED", "exit_description"=>"2 error(s) occurred:\n\n* 2 error(s) occurred:\n\n* Exited with status 2\n* cancelled\n* cancelled", "crash_count"=>3, "crash_timestamp"=>1451377821178842958, "version"=>"af8f1ed7-1c3b-4456-957a-71a927d81129"}
```

**Comment by voelzmo** [comment]
Hey @Amit-PivotalLabs,

thanks for the investigation on Diego. I haven't tried Diego, DEAs are still the default for our applications. 

Who could be logging useful information depends on what the actual error was, I guess. In the first case I described above, the DEA should log that it couldn't start the app due to insufficient quota. In the second case, I'd like to see the actual application output, although it didn't start correctly. If started locally, the app logs a pretty long stacktrace to stdout/stderr, which wasn't visible to the user. 

The second case seems to be fixed with Diego, if I interpret your example correctly. I don't know about the first one – errors that happen on the container side and prevent the application from being started correctly. Are those logged as well?

**Comment by Amit-PivotalLabs** [comment]
If you have a sample app that generates a fat jar and/or logs from the DEA/Warden when the crash happens, that would be helpful. The containers get set up with whatever limits, and then DEA drives Warden to do various things with the container; when it crashes it may not be directly clear that the cause was exceeding one of the quotas.  If Warden does not know why the underlying container crashed, or DEA is not able to find out from Warden, the issue you're describing would arise.

**Comment by Amit-PivotalLabs** [comment]
@voelzmo hey, any update on this issue?

**Comment by fraenkel** [comment]
Please re-open once you provide updates.
